/*
 * generated by Xtext
 */
package org.xtext.onec.ui.contentassist

import org.xtext.onec.ui.contentassist.AbstractOneCProposalProvider
import org.eclipse.swt.widgets.Event

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class OneCProposalProvider extends AbstractOneCProposalProvider {
	
	
	  
}
