/**
 */
package ru.awk.spb.xonec.XOneC.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ru.awk.spb.xonec.XOneC.util.XOneCAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class XOneCItemProviderAdapterFactory extends XOneCAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public XOneCItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XModuleItemProvider xModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXModuleAdapter() {
		if (xModuleItemProvider == null) {
			xModuleItemProvider = new XModuleItemProvider(this);
		}

		return xModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XVariableItemProvider xVariableItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXVariableAdapter() {
		if (xVariableItemProvider == null) {
			xVariableItemProvider = new XVariableItemProvider(this);
		}

		return xVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XMethodItemProvider xMethodItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXMethodAdapter() {
		if (xMethodItemProvider == null) {
			xMethodItemProvider = new XMethodItemProvider(this);
		}

		return xMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XParams} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XParamsItemProvider xParamsItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XParams}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXParamsAdapter() {
		if (xParamsItemProvider == null) {
			xParamsItemProvider = new XParamsItemProvider(this);
		}

		return xParamsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XParam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XParamItemProvider xParamItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XParam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXParamAdapter() {
		if (xParamItemProvider == null) {
			xParamItemProvider = new XParamItemProvider(this);
		}

		return xParamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XVariables} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XVariablesItemProvider xVariablesItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XVariables}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXVariablesAdapter() {
		if (xVariablesItemProvider == null) {
			xVariablesItemProvider = new XVariablesItemProvider(this);
		}

		return xVariablesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ru.awk.spb.xonec.XOneC.XBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XBlockItemProvider xBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ru.awk.spb.xonec.XOneC.XBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXBlockAdapter() {
		if (xBlockItemProvider == null) {
			xBlockItemProvider = new XBlockItemProvider(this);
		}

		return xBlockItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (xModuleItemProvider != null) xModuleItemProvider.dispose();
		if (xVariableItemProvider != null) xVariableItemProvider.dispose();
		if (xMethodItemProvider != null) xMethodItemProvider.dispose();
		if (xParamsItemProvider != null) xParamsItemProvider.dispose();
		if (xParamItemProvider != null) xParamItemProvider.dispose();
		if (xVariablesItemProvider != null) xVariablesItemProvider.dispose();
		if (xBlockItemProvider != null) xBlockItemProvider.dispose();
	}

}
