/*
 * generated by Xtext
 */
package org.xtext.onec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.onec.ui.internal.OneCActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OneCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OneCActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OneCActivator.getInstance().getInjector(OneCActivator.ORG_XTEXT_ONEC_ONEC);
	}
	
}
