/*
 * generated by Xtext
 */
package org.xtext.onec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;

import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OneCUiModule extends org.xtext.onec.ui.AbstractOneCUiModule {
	public OneCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Provider<IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}
	
}
