
/*
* generated by Xtext
*/
lexer grammar InternalOneCLexer;


@header {
package org.xtext.onec.parser.antlr.lexer;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}




CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIe : ('\u0412'|'\u0432')('\u042B'|'\u044B')('\u0417'|'\u0437')('\u0412'|'\u0432')('\u0410'|'\u0430')('\u0422'|'\u0442')('\u042C'|'\u044C')('\u0418'|'\u0438')('\u0421'|'\u0441')('\u041A'|'\u043A')('\u041B'|'\u043B')('\u042E'|'\u044E')('\u0427'|'\u0447')('\u0415'|'\u0435')('\u041D'|'\u043D')('\u0418'|'\u0438')('\u0415'|'\u0435');

CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeru : ('\u041A'|'\u043A')('\u041E'|'\u043E')('\u041D'|'\u043D')('\u0415'|'\u0435')('\u0426'|'\u0446')('\u041F'|'\u043F')('\u0420'|'\u0440')('\u041E'|'\u043E')('\u0426'|'\u0446')('\u0415'|'\u0435')('\u0414'|'\u0434')('\u0423'|'\u0443')('\u0420'|'\u0440')('\u042B'|'\u044B');

EndProcedure : ('E'|'e')('N'|'n')('D'|'d')('P'|'p')('R'|'r')('O'|'o')('C'|'c')('E'|'e')('D'|'d')('U'|'u')('R'|'r')('E'|'e');

Synchronized : ('S'|'s')('Y'|'y')('N'|'n')('C'|'c')('H'|'h')('R'|'r')('O'|'o')('N'|'n')('I'|'i')('Z'|'z')('E'|'e')('D'|'d');

CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterI : ('\u041A'|'\u043A')('\u041E'|'\u043E')('\u041D'|'\u043D')('\u0415'|'\u0435')('\u0426'|'\u0446')('\u041F'|'\u043F')('\u041E'|'\u043E')('\u041F'|'\u043F')('\u042B'|'\u044B')('\u0422'|'\u0442')('\u041A'|'\u043A')('\u0418'|'\u0438');

CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterI : ('\u041A'|'\u043A')('\u041E'|'\u043E')('\u041D'|'\u043D')('\u0415'|'\u0435')('\u0426'|'\u0446')('\u0424'|'\u0444')('\u0423'|'\u0443')('\u041D'|'\u043D')('\u041A'|'\u043A')('\u0426'|'\u0446')('\u0418'|'\u0438')('\u0418'|'\u0438');

CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterO : ('\u041D'|'\u043D')('\u0415'|'\u0435')('\u041E'|'\u043E')('\u041F'|'\u043F')('\u0420'|'\u0440')('\u0415'|'\u0435')('\u0414'|'\u0434')('\u0415'|'\u0435')('\u041B'|'\u043B')('\u0415'|'\u0435')('\u041D'|'\u043D')('\u041E'|'\u043E');

EndFunction : ('E'|'e')('N'|'n')('D'|'d')('F'|'f')('U'|'u')('N'|'n')('C'|'c')('T'|'t')('I'|'i')('O'|'o')('N'|'n');

Instanceof : ('I'|'i')('N'|'n')('S'|'s')('T'|'t')('A'|'a')('N'|'n')('C'|'c')('E'|'e')('O'|'o')('F'|'f');

CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIe : ('\u0418'|'\u0438')('\u0421'|'\u0441')('\u041A'|'\u043A')('\u041B'|'\u043B')('\u042E'|'\u044E')('\u0427'|'\u0447')('\u0415'|'\u0435')('\u041D'|'\u043D')('\u0418'|'\u0438')('\u0415'|'\u0435');

CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterA : ('\u041A'|'\u043A')('\u041E'|'\u043E')('\u041D'|'\u043D')('\u0415'|'\u0435')('\u0426'|'\u0446')('\u0426'|'\u0446')('\u0418'|'\u0438')('\u041A'|'\u043A')('\u041B'|'\u043B')('\u0410'|'\u0430');

CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSign : ('\u041F'|'\u043F')('\u0420'|'\u0440')('\u041E'|'\u043E')('\u0414'|'\u0434')('\u041E'|'\u043E')('\u041B'|'\u043B')('\u0416'|'\u0436')('\u0418'|'\u0438')('\u0422'|'\u0442')('\u042C'|'\u044C');

Procedure : ('P'|'p')('R'|'r')('O'|'o')('C'|'c')('E'|'e')('D'|'d')('U'|'u')('R'|'r')('E'|'e');

Undefined : ('U'|'u')('N'|'n')('D'|'d')('E'|'e')('F'|'f')('I'|'i')('N'|'n')('E'|'e')('D'|'d');

Extension : ('E'|'e')('X'|'x')('T'|'t')('E'|'e')('N'|'n')('S'|'s')('I'|'i')('O'|'o')('N'|'n');

CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterI : ('\u0418'|'\u0438')('\u041D'|'\u043D')('\u0410'|'\u0430')('\u0427'|'\u0447')('\u0415'|'\u0435')('\u0415'|'\u0435')('\u0421'|'\u0441')('\u041B'|'\u043B')('\u0418'|'\u0438');

CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterI : ('\u041A'|'\u043A')('\u041E'|'\u043E')('\u041D'|'\u043D')('\u0415'|'\u0435')('\u0426'|'\u0446')('\u0415'|'\u0435')('\u0421'|'\u0441')('\u041B'|'\u043B')('\u0418'|'\u0438');

CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterA : ('\u041F'|'\u043F')('\u0420'|'\u0440')('\u041E'|'\u043E')('\u0426'|'\u0446')('\u0415'|'\u0435')('\u0414'|'\u0434')('\u0423'|'\u0443')('\u0420'|'\u0440')('\u0410'|'\u0430');

Continue : ('C'|'c')('O'|'o')('N'|'n')('T'|'t')('I'|'i')('N'|'n')('U'|'u')('E'|'e');

Function : ('F'|'f')('U'|'u')('N'|'n')('C'|'c')('T'|'t')('I'|'i')('O'|'o')('N'|'n');

CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSign : ('\u041F'|'\u043F')('\u0420'|'\u0440')('\u0415'|'\u0435')('\u0420'|'\u0440')('\u0412'|'\u0432')('\u0410'|'\u0430')('\u0422'|'\u0442')('\u042C'|'\u044C');

Default : ('D'|'d')('E'|'e')('F'|'f')('A'|'a')('U'|'u')('L'|'l')('T'|'t');

Extends : ('E'|'e')('X'|'x')('T'|'t')('E'|'e')('N'|'n')('D'|'d')('S'|'s');

Finally : ('F'|'f')('I'|'i')('N'|'n')('A'|'a')('L'|'l')('L'|'l')('Y'|'y');

CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTe : ('\u0412'|'\u0432')('\u041E'|'\u043E')('\u0417'|'\u0437')('\u0412'|'\u0432')('\u0420'|'\u0440')('\u0410'|'\u0430')('\u0422'|'\u0442');

CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterO : ('\u041A'|'\u043A')('\u0410'|'\u0430')('\u0416'|'\u0436')('\u0414'|'\u0434')('\u041E'|'\u043E')('\u0413'|'\u0433')('\u041E'|'\u043E');

CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterI : ('\u041F'|'\u043F')('\u0415'|'\u0435')('\u0420'|'\u0440')('\u0415'|'\u0435')('\u0419'|'\u0439')('\u0422'|'\u0442')('\u0418'|'\u0438');

CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterA : ('\u041F'|'\u043F')('\u041E'|'\u043E')('\u041F'|'\u043F')('\u042B'|'\u044B')('\u0422'|'\u0442')('\u041A'|'\u043A')('\u0410'|'\u0430');

CyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterYa : ('\u0424'|'\u0444')('\u0423'|'\u0443')('\u041D'|'\u043D')('\u041A'|'\u043A')('\u0426'|'\u0446')('\u0418'|'\u0438')('\u042F'|'\u044F');

CyrillicCapitalLetterECyrillicSmallLetterKaCyrillicSmallLetterEsCyrillicSmallLetterPeCyrillicSmallLetterOCyrillicSmallLetterErCyrillicSmallLetterTe : ('\u042D'|'\u044D')('\u041A'|'\u043A')('\u0421'|'\u0441')('\u041F'|'\u043F')('\u041E'|'\u043E')('\u0420'|'\u0440')('\u0422'|'\u0442');

ElseIf : ('E'|'e')('L'|'l')('S'|'s')('E'|'e')('I'|'i')('F'|'f');

EndTry : ('E'|'e')('N'|'n')('D'|'d')('T'|'t')('R'|'r')('Y'|'y');

Except : ('E'|'e')('X'|'x')('C'|'c')('E'|'e')('P'|'p')('T'|'t');

Export : ('E'|'e')('X'|'x')('P'|'p')('O'|'o')('R'|'r')('T'|'t');

Import : ('I'|'i')('M'|'m')('P'|'p')('O'|'o')('R'|'r')('T'|'t');

Return : ('R'|'r')('E'|'e')('T'|'t')('U'|'u')('R'|'r')('N'|'n');

Static : ('S'|'s')('T'|'t')('A'|'a')('T'|'t')('I'|'i')('C'|'c');

Switch : ('S'|'s')('W'|'w')('I'|'i')('T'|'t')('C'|'c')('H'|'h');

Typeof : ('T'|'t')('Y'|'y')('P'|'p')('E'|'e')('O'|'o')('F'|'f');

CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterTeCyrillicSmallLetterICyrillicSmallLetterEnCyrillicSmallLetterA : ('\u0418'|'\u0438')('\u0421'|'\u0441')('\u0422'|'\u0442')('\u0418'|'\u0438')('\u041D'|'\u043D')('\u0410'|'\u0430');

Break : ('B'|'b')('R'|'r')('E'|'e')('A'|'a')('K'|'k');

ByVal : ('B'|'b')('Y'|'y')('V'|'v')('A'|'a')('L'|'l');

EndDo : ('E'|'e')('N'|'n')('D'|'d')('D'|'d')('O'|'o');

EndIf : ('E'|'e')('N'|'n')('D'|'d')('I'|'i')('F'|'f');

Raise : ('R'|'r')('A'|'a')('I'|'i')('S'|'s')('E'|'e');

Catch : ('C'|'c')('A'|'a')('T'|'t')('C'|'c')('H'|'h');

False : ('F'|'f')('A'|'a')('L'|'l')('S'|'s')('E'|'e');

Super : ('S'|'s')('U'|'u')('P'|'p')('E'|'e')('R'|'r');

Throw : ('T'|'t')('H'|'h')('R'|'r')('O'|'o')('W'|'w');

While_1 : ('W'|'w')('H'|'h')('I'|'i')('L'|'l')('E'|'e');

CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIe : ('\u0418'|'\u0438')('\u041D'|'\u043D')('\u0410'|'\u0430')('\u0427'|'\u0447')('\u0415'|'\u0435');

CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortI : ('\u041D'|'\u043D')('\u041E'|'\u043E')('\u0412'|'\u0432')('\u042B'|'\u044B')('\u0419'|'\u0439');

CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEm : ('\u041F'|'\u043F')('\u0415'|'\u0435')('\u0420'|'\u0440')('\u0415'|'\u0435')('\u041C'|'\u043C');

CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterA : ('\u0422'|'\u0442')('\u041E'|'\u043E')('\u0413'|'\u0433')('\u0414'|'\u0434')('\u0410'|'\u0430');

Each : ('E'|'e')('A'|'a')('C'|'c')('H'|'h');

From : ('F'|'f')('R'|'r')('O'|'o')('M'|'m');

GoTo : ('G'|'g')('O'|'o')('T'|'t')('O'|'o');

Null : ('N'|'n')('U'|'u')('L'|'l')('L'|'l');

Then : ('T'|'t')('H'|'h')('E'|'e')('N'|'n');

Case : ('C'|'c')('A'|'a')('S'|'s')('E'|'e');

Else_1 : ('E'|'e')('L'|'l')('S'|'s')('E'|'e');

True : ('T'|'t')('R'|'r')('U'|'u')('E'|'e');

CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterI : ('\u0415'|'\u0435')('\u0421'|'\u0441')('\u041B'|'\u043B')('\u0418'|'\u0438');

CyrillicCapitalLetterZeCyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterChe : ('\u0417'|'\u0437')('\u041D'|'\u043D')('\u0410'|'\u0430')('\u0427'|'\u0447');

CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSign : ('\u041B'|'\u043B')('\u041E'|'\u043E')('\u0416'|'\u0436')('\u042C'|'\u044C');

CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterA : ('\u041F'|'\u043F')('\u041E'|'\u043E')('\u041A'|'\u043A')('\u0410'|'\u0430');

CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterEl : ('\u0426'|'\u0446')('\u0418'|'\u0438')('\u041A'|'\u043A')('\u041B'|'\u043B');

AND : ('A'|'a')('N'|'n')('D'|'d');

Not : ('N'|'n')('O'|'o')('T'|'t');

For_1 : ('F'|'f')('O'|'o')('R'|'r');

New : ('N'|'n')('E'|'e')('W'|'w');

Try_1 : ('T'|'t')('R'|'r')('Y'|'y');

Val : ('V'|'v')('A'|'a')('L'|'l');

Var_1 : ('V'|'v')('A'|'a')('R'|'r');

CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYa : ('\u0414'|'\u0434')('\u041B'|'\u043B')('\u042F'|'\u044F');

CyrillicCapitalLetterICyrillicCapitalLetterElCyrillicCapitalLetterI : ('\u0418'|'\u0438')('\u041B'|'\u043B')('\u0418'|'\u0438');

PercentSignEqualsSign : '%''=';

AsteriskAsterisk : '*''*';

AsteriskEqualsSign : '*''=';

PlusSignPlusSign : '+''+';

PlusSignEqualsSign : '+''=';

HyphenMinusHyphenMinus : '-''-';

HyphenMinusEqualsSign : '-''=';

SolidusEqualsSign : '/''=';

ColonColon : ':'':';

LessThanSignGreaterThanSign : '<''>';

EqualsSignEqualsSign : '=''=';

EqualsSignGreaterThanSign : '=''>';

GreaterThanSignEqualsSign : '>''=';

QuestionMarkLeftParenthesis : '?''(';

QuestionMarkFullStop : '?''.';

OR : ('O'|'o')('R'|'r');

To : ('T'|'t')('O'|'o');

As : ('A'|'a')('S'|'s');

Do_1 : ('D'|'d')('O'|'o');

If_1 : ('I'|'i')('F'|'f');

CyrillicCapitalLetterICyrillicSmallLetterZe : ('\u0418'|'\u0438')('\u0417'|'\u0437');

CyrillicCapitalLetterEnCyrillicSmallLetterIe : ('\u041D'|'\u043D')('\u0415'|'\u0435');

CyrillicCapitalLetterPeCyrillicSmallLetterO : ('\u041F'|'\u043F')('\u041E'|'\u043E');

NumberSign : '#';

PercentSign : '%';

Ampersand : '&';

LeftParenthesis : '(';

RightParenthesis : ')';

Asterisk : '*';

PlusSign : '+';

Comma : ',';

HyphenMinus : '-';

FullStop : '.';

Solidus : '/';

Colon : ':';

Semicolon : ';';

LessThanSign : '<';

EqualsSign : '=';

GreaterThanSign : '>';

QuestionMark : '?';

LeftSquareBracket : '[';

RightSquareBracket : ']';

CircumflexAccent : '^';

LeftCurlyBracket : '{';

VerticalLine : '|';

RightCurlyBracket : '}';

CyrillicCapitalLetterI : ('\u0418'|'\u0438');



fragment RULE_DIGIT : '0'..'9';

RULE_BOM : '\uFEFF';

RULE_CONTEXT : '&' RULE_ID;

RULE_ID : (('a'..'z'|'A'..'Z'|'_'|'\u0410'..'\u042F'|'\u0401'|'\u0430'..'\u044F'|'\u0451') ('a'..'z'|'A'..'Z'|'_'|'\u0410'..'\u042F'|'\u0401'|'\u0430'..'\u044F'|'\u0451'|'0'..'9')*|'?');

RULE_DATE : '\'' RULE_DIGIT RULE_DIGIT RULE_DIGIT RULE_DIGIT '.'? RULE_DIGIT RULE_DIGIT '.'? RULE_DIGIT RULE_DIGIT ' '? (RULE_DIGIT RULE_DIGIT ':'? RULE_DIGIT RULE_DIGIT ':'? RULE_DIGIT RULE_DIGIT)? '\'';

RULE_NUMERIC : ('+'|'-')? RULE_INT '.' RULE_INT;

RULE_PREPROCESSOR : ('#' RULE_ID ( options {greedy=false;} : . )*'\n'|'#' RULE_ID EOF);

RULE_STRING : '"' ( options {greedy=false;} : . )*'"' ('"' ( options {greedy=false;} : . )*'"')*;

RULE_HEX : ('0x'|'0X') ('0'..'9'|'a'..'f'|'A'..'F'|'_')+ ('#' (('b'|'B') ('i'|'I')|('l'|'L')))?;

RULE_INT : '0'..'9' ('0'..'9'|'_')*;

RULE_DECIMAL : RULE_INT (('e'|'E') ('+'|'-')? RULE_INT)? (('b'|'B') ('i'|'I'|'d'|'D')|('l'|'L'|'d'|'D'|'f'|'F'))?;

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;



