/*
* generated by Xtext
*/
package org.xtext.onec;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OneCStandaloneSetup extends OneCStandaloneSetupGenerated{

	public static void doSetup() {
		new OneCStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

