/*
 * generated by Xtext
 */
package org.xtext.onec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OneCRuntimeModule extends org.xtext.onec.AbstractOneCRuntimeModule {
	
	
}
