/*
* generated by Xtext
*/
package org.xtext.onec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.onec.services.OneCGrammarAccess;

public class OneCParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OneCGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT", "RULE_PREPROCESSOR");
	}
	
	@Override
	protected org.xtext.onec.parser.antlr.internal.InternalOneCParser createParser(XtextTokenStream stream) {
		return new org.xtext.onec.parser.antlr.internal.InternalOneCParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public OneCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OneCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
