package org.xtext.onec.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.onec.services.OneCGrammarAccess;

@SuppressWarnings("all")
public class OneCSyntacticSequencer extends AbstractSyntacticSequencer {

	protected OneCGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Block_SemicolonKeyword_2_q;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0_or_ForKeyword_0_0_0_1;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1_or_FromKeyword_0_0_1_0_2_0;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0_or_EachKeyword_0_0_1_0_0_1;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0_or_EndDoKeyword_4_1;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1_or_WhileKeyword_0_1_0;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1_or_ToKeyword_0_0_1_1_3_0;
	protected AbstractElementAlias match_For_CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0_or_DoKeyword_2_1;
	protected AbstractElementAlias match_FormalParams_CommaKeyword_1_0_1_0_p;
	protected AbstractElementAlias match_FormalParams_CommaKeyword_1_1_p;
	protected AbstractElementAlias match_Func_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0_or_EndFunctionKeyword_9_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0_or_ElseIfKeyword_4_0_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_or_ElseKeyword_5_0_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_q_or_ElseKeyword_5_0_0_1_q;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0_or_IfKeyword_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0_or_EndIfKeyword_6_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0_or_ThenKeyword_2_0_1;
	protected AbstractElementAlias match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0_or_ThenKeyword_4_2_0_1;
	protected AbstractElementAlias match_Module_BOMTerminalRuleCall_1_q;
	protected AbstractElementAlias match_Proc_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0_or_EndProcedureKeyword_9_0_1;
	protected AbstractElementAlias match_Proc_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0_or_ProcedureKeyword_1_0_1;
	protected AbstractElementAlias match_Try_CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0_or_ExceptKeyword_3_0_1;
	protected AbstractElementAlias match_Try_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0_or_EndTryKeyword_5_1;
	protected AbstractElementAlias match_Try_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0_or_TryKeyword_1_1;
	protected AbstractElementAlias match_Vars_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0_or_VarKeyword_1_0_1;
	protected AbstractElementAlias match_Vars_SemicolonKeyword_4_q;
	protected AbstractElementAlias match_XBlockExpression_SemicolonKeyword_2_1_q;
	protected AbstractElementAlias match_XBooleanLiteral_CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2_or_FalseKeyword_1_0;
	protected AbstractElementAlias match_XConstructorCall_CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1_or_NewKeyword_1_0;
	protected AbstractElementAlias match_XExpressionInClosure_SemicolonKeyword_1_1_q;
	protected AbstractElementAlias match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q;
	protected AbstractElementAlias match_XImportDeclaration_SemicolonKeyword_2_q;
	protected AbstractElementAlias match_XNullLiteral_CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1_or_UndefinedKeyword_1_1;
	protected AbstractElementAlias match_XOperator_BreakKeyword_6_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0;
	protected AbstractElementAlias match_XOperator_ContinueKeyword_5_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0;
	protected AbstractElementAlias match_XOperator_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0_or_GoToKeyword_7_1_1;
	protected AbstractElementAlias match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1_or_ReturnKeyword_3_1_0;
	protected AbstractElementAlias match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0_or_RaiseKeyword_4_1_1;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_a;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (OneCGrammarAccess) access;
		match_Block_SemicolonKeyword_2_q = new TokenAlias(false, true, grammarAccess.getBlockAccess().getSemicolonKeyword_2());
		match_For_CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0_or_ForKeyword_0_0_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0()), new TokenAlias(false, false, grammarAccess.getForAccess().getForKeyword_0_0_0_1()));
		match_For_CyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1_or_FromKeyword_0_0_1_0_2_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1()), new TokenAlias(false, false, grammarAccess.getForAccess().getFromKeyword_0_0_1_0_2_0()));
		match_For_CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0_or_EachKeyword_0_0_1_0_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0()), new TokenAlias(false, false, grammarAccess.getForAccess().getEachKeyword_0_0_1_0_0_1()));
		match_For_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0_or_EndDoKeyword_4_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getForAccess().getEndDoKeyword_4_1()));
		match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1_or_WhileKeyword_0_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1()), new TokenAlias(false, false, grammarAccess.getForAccess().getWhileKeyword_0_1_0()));
		match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1_or_ToKeyword_0_0_1_1_3_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1()), new TokenAlias(false, false, grammarAccess.getForAccess().getToKeyword_0_0_1_1_3_0()));
		match_For_CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0_or_DoKeyword_2_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getForAccess().getCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getForAccess().getDoKeyword_2_1()));
		match_FormalParams_CommaKeyword_1_0_1_0_p = new TokenAlias(true, false, grammarAccess.getFormalParamsAccess().getCommaKeyword_1_0_1_0());
		match_FormalParams_CommaKeyword_1_1_p = new TokenAlias(true, false, grammarAccess.getFormalParamsAccess().getCommaKeyword_1_1());
		match_Func_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0_or_EndFunctionKeyword_9_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getFuncAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0()), new TokenAlias(false, false, grammarAccess.getFuncAccess().getEndFunctionKeyword_9_0_1()));
		match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0_or_ElseIfKeyword_4_0_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getElseIfKeyword_4_0_0_1()));
		match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_or_ElseKeyword_5_0_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getElseKeyword_5_0_0_1()));
		match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_q_or_ElseKeyword_5_0_0_1_q = new AlternativeAlias(false, false, new TokenAlias(false, true, grammarAccess.getIfAccess().getCyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0()), new TokenAlias(false, true, grammarAccess.getIfAccess().getElseKeyword_5_0_0_1()));
		match_If_CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0_or_IfKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getIfKeyword_0_1()));
		match_If_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0_or_EndIfKeyword_6_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getEndIfKeyword_6_0_1()));
		match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0_or_ThenKeyword_2_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getThenKeyword_2_0_1()));
		match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0_or_ThenKeyword_4_2_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIfAccess().getCyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0()), new TokenAlias(false, false, grammarAccess.getIfAccess().getThenKeyword_4_2_0_1()));
		match_Module_BOMTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getModuleAccess().getBOMTerminalRuleCall_1());
		match_Proc_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0_or_EndProcedureKeyword_9_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getProcAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0()), new TokenAlias(false, false, grammarAccess.getProcAccess().getEndProcedureKeyword_9_0_1()));
		match_Proc_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0_or_ProcedureKeyword_1_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getProcAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getProcAccess().getProcedureKeyword_1_0_1()));
		match_Try_CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0_or_ExceptKeyword_3_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTryAccess().getCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getTryAccess().getExceptKeyword_3_0_1()));
		match_Try_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0_or_EndTryKeyword_5_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTryAccess().getCyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getTryAccess().getEndTryKeyword_5_1()));
		match_Try_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0_or_TryKeyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTryAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getTryAccess().getTryKeyword_1_1()));
		match_Vars_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0_or_VarKeyword_1_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getVarsAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getVarsAccess().getVarKeyword_1_0_1()));
		match_Vars_SemicolonKeyword_4_q = new TokenAlias(false, true, grammarAccess.getVarsAccess().getSemicolonKeyword_4());
		match_XBlockExpression_SemicolonKeyword_2_1_q = new TokenAlias(false, true, grammarAccess.getXBlockExpressionAccess().getSemicolonKeyword_2_1());
		match_XBooleanLiteral_CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2_or_FalseKeyword_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXBooleanLiteralAccess().getCyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2()), new TokenAlias(false, false, grammarAccess.getXBooleanLiteralAccess().getFalseKeyword_1_0()));
		match_XConstructorCall_CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1_or_NewKeyword_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXConstructorCallAccess().getCyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getXConstructorCallAccess().getNewKeyword_1_0()));
		match_XExpressionInClosure_SemicolonKeyword_1_1_q = new TokenAlias(false, true, grammarAccess.getXExpressionInClosureAccess().getSemicolonKeyword_1_1());
		match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getLeftParenthesisKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getRightParenthesisKeyword_0_2()));
		match_XImportDeclaration_SemicolonKeyword_2_q = new TokenAlias(false, true, grammarAccess.getXImportDeclarationAccess().getSemicolonKeyword_2());
		match_XNullLiteral_CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1_or_UndefinedKeyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXNullLiteralAccess().getCyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getXNullLiteralAccess().getUndefinedKeyword_1_1()));
		match_XOperator_BreakKeyword_6_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getBreakKeyword_6_1_1()), new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0()));
		match_XOperator_ContinueKeyword_5_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getContinueKeyword_5_1_1()), new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0()));
		match_XOperator_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0_or_GoToKeyword_7_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getCyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0()), new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getGoToKeyword_7_1_1()));
		match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1_or_ReturnKeyword_3_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getCyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1()), new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getReturnKeyword_3_1_0()));
		match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0_or_RaiseKeyword_4_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getCyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0()), new TokenAlias(false, false, grammarAccess.getXOperatorAccess().getRaiseKeyword_4_1_1()));
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_a = new TokenAlias(true, true, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_p = new TokenAlias(true, false, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getArrayBracketsRule())
			return getArrayBracketsToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getBOMRule())
			return getBOMToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getOpSingleAssignRule())
			return getOpSingleAssignToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * ArrayBrackets :
	 * 	'[' ']'
	 * ;
	 */
	protected String getArrayBracketsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[]";
	}
	
	/**
	 * terminal BOM: '\uFEFF';
	 */
	protected String getBOMToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\uFEFF";
	}
	
	/**
	 * OpSingleAssign:
	 * 	"=="
	 * ;
	 */
	protected String getOpSingleAssignToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "==";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Block_SemicolonKeyword_2_q.equals(syntax))
				emit_Block_SemicolonKeyword_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0_or_ForKeyword_0_0_0_1.equals(syntax))
				emit_For_CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0_or_ForKeyword_0_0_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1_or_FromKeyword_0_0_1_0_2_0.equals(syntax))
				emit_For_CyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1_or_FromKeyword_0_0_1_0_2_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0_or_EachKeyword_0_0_1_0_0_1.equals(syntax))
				emit_For_CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0_or_EachKeyword_0_0_1_0_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0_or_EndDoKeyword_4_1.equals(syntax))
				emit_For_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0_or_EndDoKeyword_4_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1_or_WhileKeyword_0_1_0.equals(syntax))
				emit_For_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1_or_WhileKeyword_0_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1_or_ToKeyword_0_0_1_1_3_0.equals(syntax))
				emit_For_CyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1_or_ToKeyword_0_0_1_1_3_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_For_CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0_or_DoKeyword_2_1.equals(syntax))
				emit_For_CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0_or_DoKeyword_2_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_FormalParams_CommaKeyword_1_0_1_0_p.equals(syntax))
				emit_FormalParams_CommaKeyword_1_0_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_FormalParams_CommaKeyword_1_1_p.equals(syntax))
				emit_FormalParams_CommaKeyword_1_1_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Func_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0_or_EndFunctionKeyword_9_0_1.equals(syntax))
				emit_Func_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0_or_EndFunctionKeyword_9_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0_or_ElseIfKeyword_4_0_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0_or_ElseIfKeyword_4_0_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_or_ElseKeyword_5_0_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_or_ElseKeyword_5_0_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_q_or_ElseKeyword_5_0_0_1_q.equals(syntax))
				emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_q_or_ElseKeyword_5_0_0_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0_or_IfKeyword_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0_or_IfKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0_or_EndIfKeyword_6_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0_or_EndIfKeyword_6_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0_or_ThenKeyword_2_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0_or_ThenKeyword_2_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0_or_ThenKeyword_4_2_0_1.equals(syntax))
				emit_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0_or_ThenKeyword_4_2_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Module_BOMTerminalRuleCall_1_q.equals(syntax))
				emit_Module_BOMTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Proc_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0_or_EndProcedureKeyword_9_0_1.equals(syntax))
				emit_Proc_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0_or_EndProcedureKeyword_9_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Proc_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0_or_ProcedureKeyword_1_0_1.equals(syntax))
				emit_Proc_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0_or_ProcedureKeyword_1_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Try_CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0_or_ExceptKeyword_3_0_1.equals(syntax))
				emit_Try_CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0_or_ExceptKeyword_3_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Try_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0_or_EndTryKeyword_5_1.equals(syntax))
				emit_Try_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0_or_EndTryKeyword_5_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Try_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0_or_TryKeyword_1_1.equals(syntax))
				emit_Try_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0_or_TryKeyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Vars_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0_or_VarKeyword_1_0_1.equals(syntax))
				emit_Vars_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0_or_VarKeyword_1_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Vars_SemicolonKeyword_4_q.equals(syntax))
				emit_Vars_SemicolonKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XBlockExpression_SemicolonKeyword_2_1_q.equals(syntax))
				emit_XBlockExpression_SemicolonKeyword_2_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XBooleanLiteral_CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2_or_FalseKeyword_1_0.equals(syntax))
				emit_XBooleanLiteral_CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2_or_FalseKeyword_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XConstructorCall_CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1_or_NewKeyword_1_0.equals(syntax))
				emit_XConstructorCall_CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1_or_NewKeyword_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XExpressionInClosure_SemicolonKeyword_1_1_q.equals(syntax))
				emit_XExpressionInClosure_SemicolonKeyword_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q.equals(syntax))
				emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XImportDeclaration_SemicolonKeyword_2_q.equals(syntax))
				emit_XImportDeclaration_SemicolonKeyword_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XNullLiteral_CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1_or_UndefinedKeyword_1_1.equals(syntax))
				emit_XNullLiteral_CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1_or_UndefinedKeyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XOperator_BreakKeyword_6_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0.equals(syntax))
				emit_XOperator_BreakKeyword_6_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XOperator_ContinueKeyword_5_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0.equals(syntax))
				emit_XOperator_ContinueKeyword_5_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XOperator_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0_or_GoToKeyword_7_1_1.equals(syntax))
				emit_XOperator_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0_or_GoToKeyword_7_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1_or_ReturnKeyword_3_1_0.equals(syntax))
				emit_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1_or_ReturnKeyword_3_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0_or_RaiseKeyword_4_1_1.equals(syntax))
				emit_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0_or_RaiseKeyword_4_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XParenthesizedExpression_LeftParenthesisKeyword_0_a.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XParenthesizedExpression_LeftParenthesisKeyword_0_p.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Syntax:
	 *     ';'?
	 */
	protected void emit_Block_SemicolonKeyword_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Для' | 'For'
	 */
	protected void emit_For_CyrillicCapitalLetterDeCyrillicSmallLetterElCyrillicSmallLetterYaKeyword_0_0_0_0_or_ForKeyword_0_0_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'From' | 'Из'
	 */
	protected void emit_For_CyrillicCapitalLetterICyrillicSmallLetterZeKeyword_0_0_1_0_2_1_or_FromKeyword_0_0_1_0_2_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Каждого' | 'Each'
	 */
	protected void emit_For_CyrillicCapitalLetterKaCyrillicSmallLetterACyrillicSmallLetterZheCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterOKeyword_0_0_1_0_0_0_or_EachKeyword_0_0_1_0_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'КонецЦикла' | 'EndDo'
	 */
	protected void emit_For_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterAKeyword_4_0_or_EndDoKeyword_4_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'While' | 'Пока'
	 */
	protected void emit_For_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_0_1_1_or_WhileKeyword_0_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'To' | 'По'
	 */
	protected void emit_For_CyrillicCapitalLetterPeCyrillicSmallLetterOKeyword_0_0_1_1_3_1_or_ToKeyword_0_0_1_1_3_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Цикл' | 'Do'
	 */
	protected void emit_For_CyrillicCapitalLetterTseCyrillicSmallLetterICyrillicSmallLetterKaCyrillicSmallLetterElKeyword_2_0_or_DoKeyword_2_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ','+
	 */
	protected void emit_FormalParams_CommaKeyword_1_0_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ','+
	 */
	protected void emit_FormalParams_CommaKeyword_1_1_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'КонецФункции' | 'EndFunction'
	 */
	protected void emit_Func_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterEfCyrillicSmallLetterUCyrillicSmallLetterEnCyrillicSmallLetterKaCyrillicSmallLetterTseCyrillicSmallLetterICyrillicSmallLetterIKeyword_9_0_0_or_EndFunctionKeyword_9_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'ИначеЕсли' | 'ElseIf'
	 */
	protected void emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_4_0_0_0_or_ElseIfKeyword_4_0_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Иначе' | 'Else'
	 */
	protected void emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_or_ElseKeyword_5_0_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Иначе'? | 'Else'?
	 */
	protected void emit_If_CyrillicCapitalLetterICyrillicSmallLetterEnCyrillicSmallLetterACyrillicSmallLetterCheCyrillicSmallLetterIeKeyword_5_0_0_0_q_or_ElseKeyword_5_0_0_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Если' | 'If'
	 */
	protected void emit_If_CyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_0_0_or_IfKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'КонецЕсли' | 'EndIf'
	 */
	protected void emit_If_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterIeCyrillicSmallLetterEsCyrillicSmallLetterElCyrillicSmallLetterIKeyword_6_0_0_or_EndIfKeyword_6_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Тогда' | 'Then'
	 */
	protected void emit_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_2_0_0_or_ThenKeyword_2_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Тогда' | 'Then'
	 */
	protected void emit_If_CyrillicCapitalLetterTeCyrillicSmallLetterOCyrillicSmallLetterGheCyrillicSmallLetterDeCyrillicSmallLetterAKeyword_4_2_0_0_or_ThenKeyword_4_2_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     BOM?
	 */
	protected void emit_Module_BOMTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'КонецПроцедуры' | 'EndProcedure'
	 */
	protected void emit_Proc_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterYeruKeyword_9_0_0_or_EndProcedureKeyword_9_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Процедура' | 'Procedure'
	 */
	protected void emit_Proc_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterTseCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterUCyrillicSmallLetterErCyrillicSmallLetterAKeyword_1_0_0_or_ProcedureKeyword_1_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Исключение' | 'Except'
	 */
	protected void emit_Try_CyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_3_0_0_or_ExceptKeyword_3_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'КонецПопытки' | 'EndTry'
	 */
	protected void emit_Try_CyrillicCapitalLetterKaCyrillicSmallLetterOCyrillicSmallLetterEnCyrillicSmallLetterIeCyrillicSmallLetterTseCyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterIKeyword_5_0_or_EndTryKeyword_5_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Попытка' | 'Try'
	 */
	protected void emit_Try_CyrillicCapitalLetterPeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterYeruCyrillicSmallLetterTeCyrillicSmallLetterKaCyrillicSmallLetterAKeyword_1_0_or_TryKeyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Перем' | 'Var'
	 */
	protected void emit_Vars_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterEmKeyword_1_0_0_or_VarKeyword_1_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ';'?
	 */
	protected void emit_Vars_SemicolonKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ';'?
	 */
	protected void emit_XBlockExpression_SemicolonKeyword_2_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'false' | 'Ложь'
	 */
	protected void emit_XBooleanLiteral_CyrillicCapitalLetterElCyrillicSmallLetterOCyrillicSmallLetterZheCyrillicSmallLetterSoftSignKeyword_1_2_or_FalseKeyword_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'new' | 'Новый'
	 */
	protected void emit_XConstructorCall_CyrillicCapitalLetterEnCyrillicSmallLetterOCyrillicSmallLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterShortIKeyword_1_1_or_NewKeyword_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ';'?
	 */
	protected void emit_XExpressionInClosure_SemicolonKeyword_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ('(' ')')?
	 */
	protected void emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     ';'?
	 */
	protected void emit_XImportDeclaration_SemicolonKeyword_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Неопределено' | 'Undefined'
	 */
	protected void emit_XNullLiteral_CyrillicCapitalLetterEnCyrillicSmallLetterIeCyrillicSmallLetterOCyrillicSmallLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterDeCyrillicSmallLetterIeCyrillicSmallLetterElCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterOKeyword_0_1_or_UndefinedKeyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Прервать' | 'Break'
	 */
	protected void emit_XOperator_BreakKeyword_6_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_6_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Продолжить' | 'Continue'
	 */
	protected void emit_XOperator_ContinueKeyword_5_1_1_or_CyrillicCapitalLetterPeCyrillicSmallLetterErCyrillicSmallLetterOCyrillicSmallLetterDeCyrillicSmallLetterOCyrillicSmallLetterElCyrillicSmallLetterZheCyrillicSmallLetterICyrillicSmallLetterTeCyrillicSmallLetterSoftSignKeyword_5_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'Перейти' | 'GoTo'
	 */
	protected void emit_XOperator_CyrillicCapitalLetterPeCyrillicSmallLetterIeCyrillicSmallLetterErCyrillicSmallLetterIeCyrillicSmallLetterShortICyrillicSmallLetterTeCyrillicSmallLetterIKeyword_7_1_0_or_GoToKeyword_7_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'return' | 'Возврат'
	 */
	protected void emit_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterOCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterErCyrillicSmallLetterACyrillicSmallLetterTeKeyword_3_1_1_or_ReturnKeyword_3_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     'ВызватьИсключение' | 'Raise'
	 */
	protected void emit_XOperator_CyrillicCapitalLetterVeCyrillicSmallLetterYeruCyrillicSmallLetterZeCyrillicSmallLetterVeCyrillicSmallLetterACyrillicSmallLetterTeCyrillicSmallLetterSoftSignCyrillicCapitalLetterICyrillicSmallLetterEsCyrillicSmallLetterKaCyrillicSmallLetterElCyrillicSmallLetterYuCyrillicSmallLetterCheCyrillicSmallLetterIeCyrillicSmallLetterEnCyrillicSmallLetterICyrillicSmallLetterIeKeyword_4_1_0_or_RaiseKeyword_4_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     '('*
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Syntax:
	 *     '('+
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
